# Generated by Django 4.2.7 on 2025-09-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0001_initial_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classification",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("classifier.email",),
        ),
        migrations.RenameIndex(
            model_name="email",
            new_name="emails_classif_7c2d57_idx",
            old_name="emails_classification_result_idx",
        ),
        migrations.RenameIndex(
            model_name="email",
            new_name="emails_created_5daeb2_idx",
            old_name="emails_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="email",
            new_name="emails_confide_2469af_idx",
            old_name="emails_confidence_score_idx",
        ),
        migrations.AlterField(
            model_name="email",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
