# Generated by Django 5.2.5 on 2025-08-31 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifier", "0001_initial"),
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="email",
            field=models.OneToOneField(
                blank=True,
                help_text="Email associado a esta classificação.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classification",
                to="emails.email",
                verbose_name="Email",
            ),
        ),
    ]
