# Generated by Django 5.2.5 on 2025-09-02 00:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Texto completo do email enviado pelo usuário.', verbose_name='Conteúdo do Email')),
                ('subject', models.CharField(blank=True, default='Email sem assunto', help_text='Assunto do email.', max_length=255, verbose_name='Assunto')),
                ('sender_email', models.EmailField(blank=True, help_text='Email do remetente.', max_length=254, null=True, verbose_name='Email do Remetente')),
                ('recipient_email', models.EmailField(blank=True, help_text='Email do destinatário.', max_length=254, null=True, verbose_name='Email do Destinatário')),
                ('sender', models.EmailField(blank=True, help_text='Email do remetente (campo legado).', max_length=254, null=True, verbose_name='Remetente (Legacy)')),
                ('file_type', models.CharField(choices=[('text', 'Texto'), ('txt', 'Arquivo de Texto'), ('pdf', 'Arquivo PDF')], default='text', max_length=10, verbose_name='Tipo de Arquivo')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Arquivo Original')),
                ('classification', models.CharField(choices=[('spam', 'Spam'), ('legitimate', 'Legítimo'), ('unknown', 'Desconhecido'), ('phishing', 'Phishing'), ('promotional', 'Promocional')], default='unknown', help_text='Resultado da classificação por IA (campo legado).', max_length=50, verbose_name='Classificação Legada')),
                ('confidence', models.FloatField(default=0.0, help_text='Nível de confiança da classificação (0.0 a 1.0).', verbose_name='Confiança')),
                ('model_version', models.CharField(blank=True, default='v1.0', help_text='Versão do modelo de IA usado.', max_length=50, verbose_name='Versão do Modelo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('received_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Data de Recebimento')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Processamento')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_sent', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-created_at'],
            },
        ),
    ]
