# Generated by Django 5.2.5 on 2025-08-28 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Texto completo do email enviado pelo usuário.",
                        verbose_name="Conteúdo do Email",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("txt", "Arquivo de Texto"),
                            ("pdf", "Arquivo PDF"),
                        ],
                        default="text",
                        help_text="Formato do arquivo associado ao email.",
                        max_length=10,
                        verbose_name="Tipo de Arquivo",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True,
                        help_text="Nome do arquivo original (se enviado via upload).",
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Arquivo Original",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora em que o email foi enviado.",
                        verbose_name="Data de Upload",
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data e hora em que o email foi processado.",
                        null=True,
                        verbose_name="Data de Processamento",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuário que enviou o email.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email",
                "verbose_name_plural": "Emails",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
